export const ParentButtonStyle = {
    WebkitTextSizeAdjust: '100%',
    WebkitTapHighlightColor: 'rgba(0,0,0,0)',
    color: '#333',
    fontSize: '13px',
    lineHeight: '1.6',
    fontFamily: `'Open Sans', -apple-system, BlinkMacSystemFont, 'Segoe UI', 'Apple SD Gothic Neo', 'Noto Sans CJK KR', 'Noto Sans KR', '나눔바른고딕', '나눔고딕', '맑은고딕', 'Helvetica Neue', 'Helvetica', 'Arial', sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol'`,
    boxSizing: 'border-box',
    borderRadius: '0 !important',
    position: 'relative',
    minHeight: '1px',
    paddingRight: '15px',
    paddingLeft: '15px',
};

export const SubmitButtonStyle = {
    WebkitTextSizeAdjust: '100%',
    WebkitTapHighlightColor: 'rgba(0,0,0,0)',
    boxSizing: 'border-box',
    borderRadius: '0 !important',
    margin: 0,
    font: 'inherit',
    overflow: 'visible',
    textTransform: 'none',
    WebkitAppearance: 'button',
    outline: '0 !important',
    fontFamily: `'Open Sans', -apple-system, BlinkMacSystemFont, 'Segoe UI', 'Apple SD Gothic Neo', 'Noto Sans CJK KR', 'Noto Sans KR', '나눔바른고딕', '나눔고딕', '맑은고딕', 'Helvetica Neue', 'Helvetica', 'Arial', sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol' !important`,
    display: 'inline-block',
    padding: '6px 12px',
    marginBottom: 0,
    fontSize: '14px',
    fontWeight: 400,
    lineHeight: '1.42857143',
    textAlign: 'center',
    whiteSpace: 'nowrap',
    verticalAlign: 'middle',
    cursor: 'pointer',
    userSelect: 'none',
    backgroundImage: 'none',
    border: '1px solid transparent',
    color: '#fff',
    backgroundColor: '#428bca',
    borderColor: '#357ebd',
    boxShadow: 'none',
};
